baseURL = 'http://hugo-quickstart-template.netlify.com'

# Nombre del tema
theme = "LoveIt"

# Nombre del sitio

title = "DelTronik"

# Lenguaje preterminado

languageCode = "es"
languageName = "Spanish"

# Autor

[author]
	name = "DanyRdia"
	email = "danyrdia98@gmail.com"
	link = "deltronik.net"

# configuraci贸n de la barra de navegaci贸n <header bar>
[menu]

	[[menu.main]]
	weight = 1
	identifier = "posts"
	# Puede agregar contenido antes del identificador como un icono o descripci贸n, puede incluir formato html si lo desea
	pre = ""
	# Puede agregar contenido despues del identificador como un icono o descripci贸n, puede utilizar formato html si lo desea
	post = ""
	name = "Publicaciones"
	url = "/posts/"
	# el titulo se mostrara cuando el ususario acerque el mouse al identificador
	title = "Actualizaciones del blog"
